1st semester: Code Analysis, Modification and Assistance Python IDE Features
spbu-se/mag_practices_2024-2026 pull request #3
Opened 2024-12-25 22:46 UTC by i1ya-kznts9v

2024-12-26 08:17 UTC, i1ya-kznts9v commented
Добавил текст.

2025-01-08 15:43 UTC, dluciv requested changes
Титульник у отчёта

2025-01-08 15:43 UTC, dluciv commented on ПИ/Кузнецов Илья Александрович/semester_1/Kuznetsov-report.pdf
Илья, титульник поправьте плиз. Это отчёт по учебной практике, и у Вас руководитель и консультант. Ну давайте как-нибудь аккуратно уже, по содержанию-то всё норм...

2025-01-11 19:11 UTC, i1ya-kznts9v commented on ПИ/Кузнецов Илья Александрович/semester_1/Kuznetsov-report.pdf
Исправил.

2025-01-12 08:24 UTC, dluciv approved these changes

2025-01-12 08:24 UTC, merged